/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoggaInRouteImport } from './routes/logga-in'
import { Route as MittKontoRouteImport } from './routes/mitt-konto'
import { Route as SokRouteImport } from './routes/sok'
import { Route as KategoriIdRouteImport } from './routes/kategori.$id'
import { Route as MittKontoIndexRouteImport } from './routes/mitt-konto.index'
import { Route as MittKontoViewRouteImport } from './routes/mitt-konto.$view'
import { Route as ProduktIdRouteImport } from './routes/produkt.$id'
import { Route as SidaIdRouteImport } from './routes/sida.$id'
import { Route as ApiVendreSetupProgressRouteImport } from './routes/api/vendre/setup-progress'
import { Route as ApiVendreStatusRouteImport } from './routes/api/vendre/status'
import { Route as ApiVendreTokenRouteImport } from './routes/api/vendre/token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoggaInRoute = LoggaInRouteImport.update({
  id: '/logga-in',
  path: '/logga-in',
  getParentRoute: () => rootRouteImport,
} as any)
const MittKontoRoute = MittKontoRouteImport.update({
  id: '/mitt-konto',
  path: '/mitt-konto',
  getParentRoute: () => rootRouteImport,
} as any)
const SokRoute = SokRouteImport.update({
  id: '/sok',
  path: '/sok',
  getParentRoute: () => rootRouteImport,
} as any)
const KategoriIdRoute = KategoriIdRouteImport.update({
  id: '/kategori/$id',
  path: '/kategori/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MittKontoIndexRoute = MittKontoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MittKontoRoute,
} as any)
const MittKontoViewRoute = MittKontoViewRouteImport.update({
  id: '/$view',
  path: '/$view',
  getParentRoute: () => MittKontoRoute,
} as any)
const ProduktIdRoute = ProduktIdRouteImport.update({
  id: '/produkt/$id',
  path: '/produkt/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SidaIdRoute = SidaIdRouteImport.update({
  id: '/sida/$id',
  path: '/sida/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVendreSetupProgressRoute = ApiVendreSetupProgressRouteImport.update({
  id: '/api/vendre/setup-progress',
  path: '/api/vendre/setup-progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVendreStatusRoute = ApiVendreStatusRouteImport.update({
  id: '/api/vendre/status',
  path: '/api/vendre/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVendreTokenRoute = ApiVendreTokenRouteImport.update({
  id: '/api/vendre/token',
  path: '/api/vendre/token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/logga-in': typeof LoggaInRoute
  '/mitt-konto': typeof MittKontoRouteWithChildren
  '/sok': typeof SokRoute
  '/kategori/$id': typeof KategoriIdRoute
  '/mitt-konto/$view': typeof MittKontoViewRoute
  '/produkt/$id': typeof ProduktIdRoute
  '/sida/$id': typeof SidaIdRoute
  '/mitt-konto/': typeof MittKontoIndexRoute
  '/api/vendre/setup-progress': typeof ApiVendreSetupProgressRoute
  '/api/vendre/status': typeof ApiVendreStatusRoute
  '/api/vendre/token': typeof ApiVendreTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logga-in': typeof LoggaInRoute
  '/sok': typeof SokRoute
  '/kategori/$id': typeof KategoriIdRoute
  '/mitt-konto/$view': typeof MittKontoViewRoute
  '/produkt/$id': typeof ProduktIdRoute
  '/sida/$id': typeof SidaIdRoute
  '/mitt-konto': typeof MittKontoIndexRoute
  '/api/vendre/setup-progress': typeof ApiVendreSetupProgressRoute
  '/api/vendre/status': typeof ApiVendreStatusRoute
  '/api/vendre/token': typeof ApiVendreTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/logga-in': typeof LoggaInRoute
  '/mitt-konto': typeof MittKontoRouteWithChildren
  '/sok': typeof SokRoute
  '/kategori/$id': typeof KategoriIdRoute
  '/mitt-konto/$view': typeof MittKontoViewRoute
  '/produkt/$id': typeof ProduktIdRoute
  '/sida/$id': typeof SidaIdRoute
  '/mitt-konto/': typeof MittKontoIndexRoute
  '/api/vendre/setup-progress': typeof ApiVendreSetupProgressRoute
  '/api/vendre/status': typeof ApiVendreStatusRoute
  '/api/vendre/token': typeof ApiVendreTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/logga-in'
    | '/mitt-konto'
    | '/sok'
    | '/kategori/$id'
    | '/mitt-konto/$view'
    | '/produkt/$id'
    | '/sida/$id'
    | '/mitt-konto/'
    | '/api/vendre/setup-progress'
    | '/api/vendre/status'
    | '/api/vendre/token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logga-in'
    | '/sok'
    | '/kategori/$id'
    | '/mitt-konto/$view'
    | '/produkt/$id'
    | '/sida/$id'
    | '/mitt-konto'
    | '/api/vendre/setup-progress'
    | '/api/vendre/status'
    | '/api/vendre/token'
  id:
    | '__root__'
    | '/'
    | '/logga-in'
    | '/mitt-konto'
    | '/sok'
    | '/kategori/$id'
    | '/mitt-konto/$view'
    | '/produkt/$id'
    | '/sida/$id'
    | '/mitt-konto/'
    | '/api/vendre/setup-progress'
    | '/api/vendre/status'
    | '/api/vendre/token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoggaInRoute: typeof LoggaInRoute
  MittKontoRoute: typeof MittKontoRouteWithChildren
  SokRoute: typeof SokRoute
  KategoriIdRoute: typeof KategoriIdRoute
  ProduktIdRoute: typeof ProduktIdRoute
  SidaIdRoute: typeof SidaIdRoute
  ApiVendreSetupProgressRoute: typeof ApiVendreSetupProgressRoute
  ApiVendreStatusRoute: typeof ApiVendreStatusRoute
  ApiVendreTokenRoute: typeof ApiVendreTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logga-in': {
      id: '/logga-in'
      path: '/logga-in'
      fullPath: '/logga-in'
      preLoaderRoute: typeof LoggaInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitt-konto': {
      id: '/mitt-konto'
      path: '/mitt-konto'
      fullPath: '/mitt-konto'
      preLoaderRoute: typeof MittKontoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sok': {
      id: '/sok'
      path: '/sok'
      fullPath: '/sok'
      preLoaderRoute: typeof SokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kategori/$id': {
      id: '/kategori/$id'
      path: '/kategori/$id'
      fullPath: '/kategori/$id'
      preLoaderRoute: typeof KategoriIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitt-konto/': {
      id: '/mitt-konto/'
      path: '/'
      fullPath: '/mitt-konto/'
      preLoaderRoute: typeof MittKontoIndexRouteImport
      parentRoute: typeof MittKontoRoute
    }
    '/mitt-konto/$view': {
      id: '/mitt-konto/$view'
      path: '/$view'
      fullPath: '/mitt-konto/$view'
      preLoaderRoute: typeof MittKontoViewRouteImport
      parentRoute: typeof MittKontoRoute
    }
    '/produkt/$id': {
      id: '/produkt/$id'
      path: '/produkt/$id'
      fullPath: '/produkt/$id'
      preLoaderRoute: typeof ProduktIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sida/$id': {
      id: '/sida/$id'
      path: '/sida/$id'
      fullPath: '/sida/$id'
      preLoaderRoute: typeof SidaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vendre/setup-progress': {
      id: '/api/vendre/setup-progress'
      path: '/api/vendre/setup-progress'
      fullPath: '/api/vendre/setup-progress'
      preLoaderRoute: typeof ApiVendreSetupProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vendre/status': {
      id: '/api/vendre/status'
      path: '/api/vendre/status'
      fullPath: '/api/vendre/status'
      preLoaderRoute: typeof ApiVendreStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vendre/token': {
      id: '/api/vendre/token'
      path: '/api/vendre/token'
      fullPath: '/api/vendre/token'
      preLoaderRoute: typeof ApiVendreTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MittKontoRouteChildren {
  MittKontoViewRoute: typeof MittKontoViewRoute
  MittKontoIndexRoute: typeof MittKontoIndexRoute
}

const MittKontoRouteChildren: MittKontoRouteChildren = {
  MittKontoViewRoute: MittKontoViewRoute,
  MittKontoIndexRoute: MittKontoIndexRoute,
}

const MittKontoRouteWithChildren = MittKontoRoute._addFileChildren(
  MittKontoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoggaInRoute: LoggaInRoute,
  MittKontoRoute: MittKontoRouteWithChildren,
  SokRoute: SokRoute,
  KategoriIdRoute: KategoriIdRoute,
  ProduktIdRoute: ProduktIdRoute,
  SidaIdRoute: SidaIdRoute,
  ApiVendreSetupProgressRoute: ApiVendreSetupProgressRoute,
  ApiVendreStatusRoute: ApiVendreStatusRoute,
  ApiVendreTokenRoute: ApiVendreTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
