/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KategoriSlugRouteImport } from './routes/kategori.$slug'
import { Route as ProduktSlugRouteImport } from './routes/produkt.$slug'
import { Route as ApiVendreStatusRouteImport } from './routes/api/vendre/status'
import { Route as ApiVendreTokenRouteImport } from './routes/api/vendre/token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KategoriSlugRoute = KategoriSlugRouteImport.update({
  id: '/kategori/$slug',
  path: '/kategori/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduktSlugRoute = ProduktSlugRouteImport.update({
  id: '/produkt/$slug',
  path: '/produkt/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVendreStatusRoute = ApiVendreStatusRouteImport.update({
  id: '/api/vendre/status',
  path: '/api/vendre/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVendreTokenRoute = ApiVendreTokenRouteImport.update({
  id: '/api/vendre/token',
  path: '/api/vendre/token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kategori/$slug': typeof KategoriSlugRoute
  '/produkt/$slug': typeof ProduktSlugRoute
  '/api/vendre/status': typeof ApiVendreStatusRoute
  '/api/vendre/token': typeof ApiVendreTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kategori/$slug': typeof KategoriSlugRoute
  '/produkt/$slug': typeof ProduktSlugRoute
  '/api/vendre/status': typeof ApiVendreStatusRoute
  '/api/vendre/token': typeof ApiVendreTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kategori/$slug': typeof KategoriSlugRoute
  '/produkt/$slug': typeof ProduktSlugRoute
  '/api/vendre/status': typeof ApiVendreStatusRoute
  '/api/vendre/token': typeof ApiVendreTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kategori/$slug'
    | '/produkt/$slug'
    | '/api/vendre/status'
    | '/api/vendre/token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kategori/$slug'
    | '/produkt/$slug'
    | '/api/vendre/status'
    | '/api/vendre/token'
  id:
    | '__root__'
    | '/'
    | '/kategori/$slug'
    | '/produkt/$slug'
    | '/api/vendre/status'
    | '/api/vendre/token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KategoriSlugRoute: typeof KategoriSlugRoute
  ProduktSlugRoute: typeof ProduktSlugRoute
  ApiVendreStatusRoute: typeof ApiVendreStatusRoute
  ApiVendreTokenRoute: typeof ApiVendreTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kategori/$slug': {
      id: '/kategori/$slug'
      path: '/kategori/$slug'
      fullPath: '/kategori/$slug'
      preLoaderRoute: typeof KategoriSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produkt/$slug': {
      id: '/produkt/$slug'
      path: '/produkt/$slug'
      fullPath: '/produkt/$slug'
      preLoaderRoute: typeof ProduktSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vendre/status': {
      id: '/api/vendre/status'
      path: '/api/vendre/status'
      fullPath: '/api/vendre/status'
      preLoaderRoute: typeof ApiVendreStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vendre/token': {
      id: '/api/vendre/token'
      path: '/api/vendre/token'
      fullPath: '/api/vendre/token'
      preLoaderRoute: typeof ApiVendreTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KategoriSlugRoute: KategoriSlugRoute,
  ProduktSlugRoute: ProduktSlugRoute,
  ApiVendreStatusRoute: ApiVendreStatusRoute,
  ApiVendreTokenRoute: ApiVendreTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
