/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoryIdRouteImport } from './routes/category.$id'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as ApiVendreStatusRouteImport } from './routes/api/vendre/status'
import { Route as ApiVendreTokenRouteImport } from './routes/api/vendre/token'
import { Route as ApiVendreProxySplatRouteImport } from './routes/api/vendre/proxy.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryIdRoute = CategoryIdRouteImport.update({
  id: '/category/$id',
  path: '/category/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVendreStatusRoute = ApiVendreStatusRouteImport.update({
  id: '/api/vendre/status',
  path: '/api/vendre/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVendreTokenRoute = ApiVendreTokenRouteImport.update({
  id: '/api/vendre/token',
  path: '/api/vendre/token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVendreProxySplatRoute = ApiVendreProxySplatRouteImport.update({
  id: '/api/vendre/proxy/$',
  path: '/api/vendre/proxy/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/category/$id': typeof CategoryIdRoute
  '/product/$id': typeof ProductIdRoute
  '/api/vendre/status': typeof ApiVendreStatusRoute
  '/api/vendre/token': typeof ApiVendreTokenRoute
  '/api/vendre/proxy/$': typeof ApiVendreProxySplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/category/$id': typeof CategoryIdRoute
  '/product/$id': typeof ProductIdRoute
  '/api/vendre/status': typeof ApiVendreStatusRoute
  '/api/vendre/token': typeof ApiVendreTokenRoute
  '/api/vendre/proxy/$': typeof ApiVendreProxySplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/category/$id': typeof CategoryIdRoute
  '/product/$id': typeof ProductIdRoute
  '/api/vendre/status': typeof ApiVendreStatusRoute
  '/api/vendre/token': typeof ApiVendreTokenRoute
  '/api/vendre/proxy/$': typeof ApiVendreProxySplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/category/$id'
    | '/product/$id'
    | '/api/vendre/status'
    | '/api/vendre/token'
    | '/api/vendre/proxy/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/category/$id'
    | '/product/$id'
    | '/api/vendre/status'
    | '/api/vendre/token'
    | '/api/vendre/proxy/$'
  id:
    | '__root__'
    | '/'
    | '/category/$id'
    | '/product/$id'
    | '/api/vendre/status'
    | '/api/vendre/token'
    | '/api/vendre/proxy/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoryIdRoute: typeof CategoryIdRoute
  ProductIdRoute: typeof ProductIdRoute
  ApiVendreStatusRoute: typeof ApiVendreStatusRoute
  ApiVendreTokenRoute: typeof ApiVendreTokenRoute
  ApiVendreProxySplatRoute: typeof ApiVendreProxySplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$id': {
      id: '/category/$id'
      path: '/category/$id'
      fullPath: '/category/$id'
      preLoaderRoute: typeof CategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vendre/status': {
      id: '/api/vendre/status'
      path: '/api/vendre/status'
      fullPath: '/api/vendre/status'
      preLoaderRoute: typeof ApiVendreStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vendre/token': {
      id: '/api/vendre/token'
      path: '/api/vendre/token'
      fullPath: '/api/vendre/token'
      preLoaderRoute: typeof ApiVendreTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vendre/proxy/$': {
      id: '/api/vendre/proxy/$'
      path: '/api/vendre/proxy/$'
      fullPath: '/api/vendre/proxy/$'
      preLoaderRoute: typeof ApiVendreProxySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoryIdRoute: CategoryIdRoute,
  ProductIdRoute: ProductIdRoute,
  ApiVendreStatusRoute: ApiVendreStatusRoute,
  ApiVendreTokenRoute: ApiVendreTokenRoute,
  ApiVendreProxySplatRoute: ApiVendreProxySplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
